LECHAT_WEB_RAYGUN_API_KEY='Acuqb1BJ+nM8+PCDctHf1Q==';
LECHAT_WEB_RAYGUN_ENVIROMENT='prod';
LECHAT_PASTE_S3_BASE_LEGACY='https://s3.amazonaws.com/kato-paste/';
LECHAT_RELEASE_VERSION='005b2b1';
LECHAT_DEBUG={};
